"""Install one project-owned Vicinae script, preserving all existing commands."""
from pathlib import Path
import shlex
import subprocess
import sys
root=Path(__file__).resolve().parents[2]
subprocess.run(['bash',str(root/'integrations/vicinae/build.sh')],check=True)
target=Path.home()/'.local/share/vicinae/scripts/wanjiegate-intent.sh'
marker='# Generated by WanjieGate intent integration'
if target.exists() and marker not in target.read_text():raise SystemExit('目标脚本已存在且不属于本项目，未覆盖')
body='''#!/bin/bash
# Generated by WanjieGate intent integration
# @vicinae.schemaVersion 1
# @vicinae.title 万界门 · 意图泡泡
# @vicinae.mode silent
# @vicinae.argument1 {"type":"text","placeholder":"输入一句想法（可留空）","optional":true}
set -euo pipefail
'''
body+='exec '+shlex.quote(sys.executable)+' '+shlex.quote(str(root/'integrations/vicinae/launch.py'))+' "${1:-}"\n'
# Validate before registering with Vicinae's watched script directory.
staging=root/'.data/wanjiegate-intent.sh';staging.write_text(body);staging.chmod(0o755)
cli='/Applications/Vicinae.app/Contents/MacOS/vicinae-cli'
subprocess.run([cli,'script','check',str(staging)],check=True)
target.parent.mkdir(parents=True,exist_ok=True);target.write_text(body);target.chmod(0o755)
subprocess.run([cli,'cmd','launch','core:reload-scripts'],check=True)
print('Installed:',target)
