import assert from 'node:assert/strict';
import fs from 'node:fs';
import {LivePreview} from '../static/js/live-preview.js';
import {liveSurfaces} from '../static/js/live-surface.js';
import {sceneSurfaces} from '../static/js/scene.js';
import {infer,planFrom,selectComponents} from '../static/js/composition.js';
const r=JSON.parse(fs.readFileSync(new URL('../static/registry.json',import.meta.url)));
const tick=()=>new Promise(resolve=>setImmediate(resolve));
let calls=[], applied=[], pending=[];
const live=new LivePreview(text=>{calls.push(text);return new Promise((resolve,reject)=>pending.push({resolve,reject}));},result=>applied.push(result));
live.update('写');
assert.deepEqual(calls,['写'],'first character dispatches immediately');
live.update('写一'); live.update('写一篇');
assert.equal(calls.length,1,'only one in-flight request');
pending[0].resolve('stale'); await tick();
assert.deepEqual(calls,['写','写一篇'],'queue keeps only newest input');
assert.deepEqual(applied,[],'old response never changes UI');
pending[1].resolve('current'); await tick();
assert.deepEqual(applied,['current']);
live.update('计划'); live.clear(); pending[2].resolve('cleared'); await tick();
assert.deepEqual(applied,['current'],'clear prevents old response restoring UI');
live.update('first'); live.update('latest'); pending[3].reject(new Error('offline')); await tick();
assert.equal(calls.at(-1),'latest','failure drains the newest request');
pending[4].resolve('recovered'); await tick();
assert.equal(applied.at(-1),'recovered');
const plan=planFrom(infer('写文章并列计划',r),r,false);
const surfaces=liveSurfaces(plan,selectComponents(plan,r),'<script>unsafe</script>',null);
assert.deepEqual(surfaces,[],'never mirror input as generated content');
assert(surfaces.every(s=>!s.html.includes('<script>')));
const scene=sceneSurfaces({status:'ready',blocks:[{type:'text',text:'<script>unsafe</script>'},{type:'tasks',items:['真正生成的任务']}]});
assert(scene.every(s=>!s.html.includes('<script>')));
assert(scene.some(s=>s.html.includes('真正生成的任务')));
console.log('PASS: immediate dispatch, latest input queue, stale/clear/failure isolation, live component composition');
