import assert from 'node:assert/strict';
import {destinationFor,previewContent} from '../static/js/bubbles/handoff.mjs';
const b={id:'a',kind:'action',title:'写草稿',resource:{action:'write'}};
assert.equal(destinationFor([b],{}),null);
assert.equal(destinationFor([b],{writing:'https://example.com/editor'}).url,'https://example.com/editor');
assert.equal(destinationFor([{kind:'link',resource:{url:'javascript:alert(1)'}}],{}),null);
assert.equal(destinationFor([{kind:'link',resource:{url:'https://example.com/page'}}],{}).url,'https://example.com/page');
assert.equal(destinationFor([{kind:'source',resource:{market:'sh000001'}}],{market:'https://example.com/quotes'}).url,'https://example.com/quotes');
assert.match(previewContent({title:'组合'},[b,{title:'资料',resource:{artifact:'n'}}],{artifacts:[{id:'n',content:{text:'具体原文'}}]}),/具体原文/);
console.log('handoff routing and preview passed');
assert.deepEqual(destinationFor([b],{writing:'obsidian',vault:'abc'}),{kind:'obsidian',vault:'abc'});
assert.equal(destinationFor([b],{writing:'obsidian'}),null);
assert.equal(destinationFor([{scene:'learning',resource:{action:'quiz'}}],{writing:'https://example.com/writing'}),null);
assert.equal(destinationFor([{scene:'development',resource:{action:'code'}}],{development:'https://example.com/dev'}).kind,'development');
assert.equal(destinationFor([{resource:{artifact:'quote'}}],{writing:'https://example.com/writing',market:'https://example.com/market'},{artifacts:[{id:'quote',kind:'market',content:{}}]}).kind,'market');
assert.equal(destinationFor([{scene:'learning',resource:{action:'quiz'}},{scene:'market',resource:{action:'research'}}],{market:'https://example.com/market'}),null);
const {handoffContent}=await import('../static/js/bubbles/handoff.mjs');
assert.match(handoffContent({title:'学习'},[{title:'出题',request:'出五道题，先别给答案',resource:{action:'quiz'}}],{}),/先别给答案/);
assert.equal(destinationFor([{resource:{artifact:'quote'}}],{market:'https://example.com/market'},{artifacts:[{id:'quote',kind:'scene',content:{blocks:[{type:'quotes'}]}}]}).kind,'market');
assert.match(previewContent({title:'行情'},[{resource:{artifact:'q'}}],{artifacts:[{id:'q',source:'报价来源',version:2,content:{blocks:[{type:'quotes',items:[{symbol:'ABC',price:10}]}]}}]}),/ABC/);
const reusedNote={kind:'source',title:'笔记',scene:'writing',request:'写读后感',resource:{artifact:'note'}};
const quizAction={kind:'action',title:'出题',scene:'learning',request:'出五题不给答案',resource:{action:'quiz'}};
assert.equal(destinationFor([reusedNote,quizAction],{learning:'https://example.com/study'}).kind,'learning');
assert.doesNotMatch(handoffContent({title:'笔记与出题'},[reusedNote,quizAction],{}),/写读后感/);

assert.equal(destinationFor([{resource:{artifact:'note'}}],{writing:'obsidian',vault:'abc'},{artifacts:[{id:'note',kind:'note'}]}).kind,'obsidian');
const {applyDetectedTools}=await import('../static/js/bubbles/handoff.mjs');
const detected={defaults:{learning:'app:kimi',market:'app:stocks',writing:'app:notes'},obsidian:{installed:true,vaults:[{id:'one',name:'Notes'}]}};
assert.equal(applyDetectedTools({learning:'https://my.example/study'},detected).learning,'https://my.example/study');
assert.equal(applyDetectedTools({},detected).writing,'obsidian');
assert.equal(destinationFor([{scene:'learning',resource:{action:'quiz'}}],{learning:'app:kimi'}).tool,'kimi');
assert.equal(destinationFor([{scene:'learning',resource:{action:'quiz'}}],{learning:'app:../../bad'}),null);
